---
- name: Resolving {{ kubernetes_persona }} vars
  ansible.builtin.include_vars:
    file: install-persona-vars.yml

- name: Installing {{ kubernetes_persona }} OS pkg runtime dependencies
  become: '{{ kubernetes_escalate_privilege }}'
  become_user: root
  ansible.builtin.package:
    name: '{{ kubernetes_persona_os_dep_pkgs }}'
    state: present

- name: Checking for {{ kubernetes_persona }} installation at {{ kubernetes_persona_bin_dir }}
  ansible.builtin.stat:
    path: '{{ kubernetes_persona_bin_dir }}'
  changed_when: false
  register: kubernetes_persona_binary
- name: Downloading and installing kubernetes binaries
  when: not kubernetes_persona_binary.stat.exists
  block:
    - name: Downloading {{ kubernetes_persona }} binaries from {{ kubernetes_tgz_url }}
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      ansible.builtin.get_url:
        url: '{{ kubernetes_tgz_url }}'
        dest: '{{ kubernetes_tmp_tgz }}'
        checksum: '{{ kubernetes_checksum }}'
        mode: '644'

    - name: Extracting {{ kubernetes_persona }} binaries to {{ kubernetes_install_path }}
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ kubernetes_tmp_tgz }}'
        dest: '{{ kubernetes_install_path }}'
        creates: '{{ kubernetes_persona_bin_dir }}'

    - name: Making {{ kubernetes_persona }} binary directories world readable
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      with_items: '{{ kubernetes_persona_dirs }}'
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '755'

    - name: Making {{ kubernetes_persona }} binaries in {{ kubernetes_persona_bin_dir }} world executable
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      with_items: '{{ kubernetes_persona_binaries }}'
      ansible.builtin.file:
        path: '{{ kubernetes_persona_bin_dir }}/{{ item }}'
        state: file
        mode: '755'
  always:
    - name: Rm {{ kubernetes_tmp_tgz }}
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      ansible.builtin.file:
        path: '{{ kubernetes_tmp_tgz }}'
        state: absent

- name: Linking {{ kubernetes_persona }} binaries in {{ kubernetes_persona_bin_dir }} from {{ kubernetes_install_dir }}
  become: '{{ kubernetes_escalate_privilege }}'
  become_user: root
  with_items: '{{ kubernetes_persona_binaries }}'
  ansible.builtin.file:
    src: '{{ kubernetes_persona_bin_dir }}/{{ item }}'
    dest: '{{ kubernetes_install_dir }}/{{ item }}'
    state: link
