---
- name: resolving {{ kubernetes_persona }} vars
  include_vars:
    file: install-persona-vars.yml

- name: installing {{ kubernetes_persona }} OS pkg runtime dependencies
  become: '{{ kubernetes_escalate_privilege }}'
  become_user: root
  package:
    name: '{{ kubernetes_persona_os_dep_pkgs }}'
    state: present

- name: checking for {{ kubernetes_persona }} installation at {{ kubernetes_persona_bin_dir }}
  stat:
    path: '{{ kubernetes_persona_bin_dir }}'
  changed_when: false
  register: kubernetes_persona_binary
- when: not kubernetes_persona_binary.stat.exists
  block:
    - name: downloading {{ kubernetes_persona }} binaries from {{ kubernetes_tgz_url }}
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      get_url:
        url: '{{ kubernetes_tgz_url }}'
        dest: '{{ kubernetes_tmp_tgz }}'
        checksum: '{{ kubernetes_checksum }}'
        mode: 0644

    - name: extracting {{ kubernetes_persona }} binaries to {{ kubernetes_install_path }}
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ kubernetes_tmp_tgz }}'
        dest: '{{ kubernetes_install_path }}'
        creates: '{{ kubernetes_persona_bin_dir }}'

    - name: making {{ kubernetes_persona }} binary directories world readable
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      with_items: '{{ kubernetes_persona_dirs }}'
      file:
        path: '{{ item }}'
        state: directory
        mode: 0755

    - name: making {{ kubernetes_persona }} binaries in {{ kubernetes_persona_bin_dir }} world executable
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      with_items: '{{ kubernetes_persona_binaries }}'
      file:
        path: '{{ kubernetes_persona_bin_dir }}/{{ item }}'
        state: file
        mode: 0755
  always:
    - name: rm {{ kubernetes_tmp_tgz }}
      become: '{{ kubernetes_escalate_privilege }}'
      become_user: root
      file:
        path: '{{ kubernetes_tmp_tgz }}'
        state: absent

- name: linking {{ kubernetes_persona }} binaries in {{ kubernetes_persona_bin_dir }} from {{ kubernetes_install_dir }}
  become: '{{ kubernetes_escalate_privilege }}'
  become_user: root
  with_items: '{{ kubernetes_persona_binaries }}'
  file:
    src: '{{ kubernetes_persona_bin_dir }}/{{ item }}'
    dest: '{{ kubernetes_install_dir }}/{{ item }}'
    state: link
